#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=0

start() {
	local enable
	/usr/sbin/nsclient sync >/dev/null 2>&1 || true
	enable=$(uci -q get nsclient.main.enable)
	[ "$enable" = "1" ] || return 0
	/usr/sbin/nsclient autostart
}

stop() {
	/usr/sbin/nsclient disconnect >/dev/null 2>&1 || true
}

reload() {
	stop
	start
}

restart() {
	stop
	start
}
