#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
	/usr/sbin/nsclient sync >/dev/null 2>&1 || true
	procd_open_instance
	procd_set_param command /usr/sbin/nsclient watch
	procd_set_param respawn 3600 10 0
	procd_close_instance
}

stop_service() {
	KEEP_WANT=1 /usr/sbin/nsclient disconnect >/dev/null 2>&1 || true
}
